parameters:
    product_service_url: '%env(PRODUCT_SERVICE_URL)%'
    user_service_url: '%env(USER_SERVICE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # اسکن خودکار کل پوشه src/
    App\:
        resource: '../src/'

    # HealthChecks به جز فایل‌هایی که دستی مقداردهی می‌کنیم
    App\HealthCheck\:
        resource: '../src/HealthCheck/*'
        exclude:
            - '../src/HealthCheck/ProductServiceHealth.php'
            - '../src/HealthCheck/UserServiceHealth.php'
        tags: ['app.health_checker']

    # ProductServiceHealth - تزریق URL از .env
    App\HealthCheck\ProductServiceHealth:
        arguments:
            $url: '%env(PRODUCT_SERVICE_URL)%'
        tags: ['app.health_checker']

    # UserServiceHealth - تزریق URL از .env
    App\HealthCheck\UserServiceHealth:
        arguments:
            $url: '%env(USER_SERVICE_URL)%'
        tags: ['app.health_checker']

    # Aggregator
    App\HealthCheck\HealthAggregator:
        arguments:
            - !tagged_iterator 'app.health_checker'
